### ISSUE TITLE
Analyze stack to use

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-price-service#1]
- A clear requirement is that we use Python, so we can reuse project from https://github.com/safe-global/safe-transaction-service/ .
- We must decide if we continue with Django or test another framework like FastAPI.

**Comment by Uxio0** [comment]
## Django
### Pros
- We already have a lot of expertise.
- We can use same configuration, flows, etc. from the tx-service.
- Gevent gives us async features even for not compatible libraries.
- If we need to use the database good ORM, built in migrations and amazing admin panel.
- Stable and well maintained.
- A lot of people know Django.
### Cons
- Slower than FastAPI.
- Not learning a new technology.
- More boilerplate.

## Flask
### Pros
- Simpler.
- Faster than Django in some scenarios.
- Less boilerplate than Django.
### Cons
- Need to build a lot of things around to make it work

## FastAPI
### Pros
- Modern framework (typing, concurrency, simpler...)
- Faster than Django
- Async oriented
- Learning a new framework
### Cons
- Time of learning a new framework
- Multiple developed things on the price service count on gevent and not on Python default async
- Database, Celery, etc. can be integrated but need some work
- One person project

I think Django would be the tool for our task, but I would like to have @moisses89 opinion before closing the issue

**Comment by moisses89** [comment]
I'm between FastAPI and Django, I wouldn't consider flask to this service because maybe need a lot of extra work and maintenance. 
For me the biggest con of FastAPI is that is mainly maintained by one person as you mentioned in your cons and also I prefer the Django migrations if we need database. 
Then thinking that we want to move fast with the first version of this service, I'd say also Django.
